name: Feature request
description: Suggest an improvement or new capability
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion!

        Please keep requests focused on the project scope (free/busy normalization and a minimal, safe API).

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the underlying need (not the solution yet).
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe what you’d like to change.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered.
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope / compatibility
      description: Any constraints? (breaking changes, OpenAPI updates, deployment concerns, etc.)
    validations:
      required: false
